CREATE LOGIN [NT AUTHORITY\IUSR] 
	FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO
CREATE LOGIN [NT AUTHORITY\SYSTEM] 
	FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO
CREATE LOGIN [IIS AppPool\DefaultAppPool] 
	FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english];
GO
