//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace PSNC.RepoAV.Recoder {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.psnc.pl/Recoder/RecoderTaskDefinition/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Tasks", Namespace="http://schemas.psnc.pl/Recoder/RecoderTaskDefinition/1.0", IsNullable=false)]
    public partial class TaskCollection {
        
        private TaskDefinition[] taskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Task")]
        public TaskDefinition[] Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.psnc.pl/Recoder/RecoderTaskDefinition/1.0")]
    public partial class TaskDefinition {
        
        private OperationDefinition[] operationsField;
        
        private string nameField;
        
        private string startOperationField;
        
        private int executionTimeoutField;
        
        public TaskDefinition() {
            this.executionTimeoutField = 3600;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable=false)]
        public OperationDefinition[] Operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartOperation {
            get {
                return this.startOperationField;
            }
            set {
                this.startOperationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(3600)]
        public int ExecutionTimeout {
            get {
                return this.executionTimeoutField;
            }
            set {
                this.executionTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.psnc.pl/Recoder/RecoderTaskDefinition/1.0")]
    public partial class OperationDefinition {
        
        private string nameField;
        
        private bool skipField;
        
        private SkipResults skipResultField;
        
        private bool skipResultFieldSpecified;
               
        private string onSuccessField;
        
        private string onFailureField;
        
        private string valueField;
        
        public OperationDefinition() {
            this.skipField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Skip {
            get {
                return this.skipField;
            }
            set {
                this.skipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SkipResults SkipResult {
            get {
                return this.skipResultField;
            }
            set {
                this.skipResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SkipResultSpecified {
            get {
                return this.skipResultFieldSpecified;
            }
            set {
                this.skipResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OnSuccess {
            get {
                return this.onSuccessField;
            }
            set {
                this.onSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OnFailure {
            get {
                return this.onFailureField;
            }
            set {
                this.onFailureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.psnc.pl/Recoder/RecoderTaskDefinition/1.0")]
    public enum SkipResults {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        StopExecutionWithSuccess,
        
        /// <remarks/>
        StopExecutionWithFailure,
    }    
}
